// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.14.0
// source: oneRobot/v1/robot.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 一问一答 - 问
type CreateQuestionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserUuid string `protobuf:"bytes,1,opt,name=userUuid,proto3" json:"userUuid,omitempty"`
	OrgUuid  string `protobuf:"bytes,2,opt,name=orgUuid,proto3" json:"orgUuid,omitempty"`
	Question string `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
}

func (x *CreateQuestionReq) Reset() {
	*x = CreateQuestionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneRobot_v1_robot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQuestionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionReq) ProtoMessage() {}

func (x *CreateQuestionReq) ProtoReflect() protoreflect.Message {
	mi := &file_oneRobot_v1_robot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionReq.ProtoReflect.Descriptor instead.
func (*CreateQuestionReq) Descriptor() ([]byte, []int) {
	return file_oneRobot_v1_robot_proto_rawDescGZIP(), []int{0}
}

func (x *CreateQuestionReq) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *CreateQuestionReq) GetOrgUuid() string {
	if x != nil {
		return x.OrgUuid
	}
	return ""
}

func (x *CreateQuestionReq) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type CreateQuestionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
}

func (x *CreateQuestionReply) Reset() {
	*x = CreateQuestionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneRobot_v1_robot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQuestionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionReply) ProtoMessage() {}

func (x *CreateQuestionReply) ProtoReflect() protoreflect.Message {
	mi := &file_oneRobot_v1_robot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionReply.ProtoReflect.Descriptor instead.
func (*CreateQuestionReply) Descriptor() ([]byte, []int) {
	return file_oneRobot_v1_robot_proto_rawDescGZIP(), []int{1}
}

func (x *CreateQuestionReply) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 一问一答 - 答
type GetAnswerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserUuid string `protobuf:"bytes,1,opt,name=userUuid,proto3" json:"userUuid,omitempty"`
	OrgUuid  string `protobuf:"bytes,2,opt,name=orgUuid,proto3" json:"orgUuid,omitempty"`
	TaskId   string `protobuf:"bytes,3,opt,name=taskId,proto3" json:"taskId,omitempty"`
}

func (x *GetAnswerReq) Reset() {
	*x = GetAnswerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneRobot_v1_robot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnswerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswerReq) ProtoMessage() {}

func (x *GetAnswerReq) ProtoReflect() protoreflect.Message {
	mi := &file_oneRobot_v1_robot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswerReq.ProtoReflect.Descriptor instead.
func (*GetAnswerReq) Descriptor() ([]byte, []int) {
	return file_oneRobot_v1_robot_proto_rawDescGZIP(), []int{2}
}

func (x *GetAnswerReq) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GetAnswerReq) GetOrgUuid() string {
	if x != nil {
		return x.OrgUuid
	}
	return ""
}

func (x *GetAnswerReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetAnswerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionUuid string `protobuf:"bytes,1,opt,name=sessionUuid,proto3" json:"sessionUuid,omitempty"`
	Question    string `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Answer      string `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"` // Reply
	Result      int32  `protobuf:"varint,4,opt,name=result,proto3" json:"result,omitempty"`
	Assistant   int32  `protobuf:"varint,5,opt,name=assistant,proto3" json:"assistant,omitempty"`
	CreateTime  int64  `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
}

func (x *GetAnswerReply) Reset() {
	*x = GetAnswerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneRobot_v1_robot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnswerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswerReply) ProtoMessage() {}

func (x *GetAnswerReply) ProtoReflect() protoreflect.Message {
	mi := &file_oneRobot_v1_robot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswerReply.ProtoReflect.Descriptor instead.
func (*GetAnswerReply) Descriptor() ([]byte, []int) {
	return file_oneRobot_v1_robot_proto_rawDescGZIP(), []int{3}
}

func (x *GetAnswerReply) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

func (x *GetAnswerReply) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *GetAnswerReply) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *GetAnswerReply) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *GetAnswerReply) GetAssistant() int32 {
	if x != nil {
		return x.Assistant
	}
	return 0
}

func (x *GetAnswerReply) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// 获取历史提问
type GetQuestionHisReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserUuid string `protobuf:"bytes,1,opt,name=userUuid,proto3" json:"userUuid,omitempty"`
	OrgUuid  string `protobuf:"bytes,2,opt,name=orgUuid,proto3" json:"orgUuid,omitempty"`
}

func (x *GetQuestionHisReq) Reset() {
	*x = GetQuestionHisReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneRobot_v1_robot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuestionHisReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionHisReq) ProtoMessage() {}

func (x *GetQuestionHisReq) ProtoReflect() protoreflect.Message {
	mi := &file_oneRobot_v1_robot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionHisReq.ProtoReflect.Descriptor instead.
func (*GetQuestionHisReq) Descriptor() ([]byte, []int) {
	return file_oneRobot_v1_robot_proto_rawDescGZIP(), []int{4}
}

func (x *GetQuestionHisReq) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GetQuestionHisReq) GetOrgUuid() string {
	if x != nil {
		return x.OrgUuid
	}
	return ""
}

type GetQuestionHisReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Questions []*GetQuestionHisReply_Question `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
}

func (x *GetQuestionHisReply) Reset() {
	*x = GetQuestionHisReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneRobot_v1_robot_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuestionHisReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionHisReply) ProtoMessage() {}

func (x *GetQuestionHisReply) ProtoReflect() protoreflect.Message {
	mi := &file_oneRobot_v1_robot_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionHisReply.ProtoReflect.Descriptor instead.
func (*GetQuestionHisReply) Descriptor() ([]byte, []int) {
	return file_oneRobot_v1_robot_proto_rawDescGZIP(), []int{5}
}

func (x *GetQuestionHisReply) GetQuestions() []*GetQuestionHisReply_Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

//
type CreateChatSessionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SystemRole string `protobuf:"bytes,1,opt,name=systemRole,proto3" json:"systemRole,omitempty"`
}

func (x *CreateChatSessionReq) Reset() {
	*x = CreateChatSessionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneRobot_v1_robot_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatSessionReq) ProtoMessage() {}

func (x *CreateChatSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_oneRobot_v1_robot_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatSessionReq.ProtoReflect.Descriptor instead.
func (*CreateChatSessionReq) Descriptor() ([]byte, []int) {
	return file_oneRobot_v1_robot_proto_rawDescGZIP(), []int{6}
}

func (x *CreateChatSessionReq) GetSystemRole() string {
	if x != nil {
		return x.SystemRole
	}
	return ""
}

type CreateChatSessionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CreateChatSessionReply) Reset() {
	*x = CreateChatSessionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneRobot_v1_robot_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatSessionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatSessionReply) ProtoMessage() {}

func (x *CreateChatSessionReply) ProtoReflect() protoreflect.Message {
	mi := &file_oneRobot_v1_robot_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatSessionReply.ProtoReflect.Descriptor instead.
func (*CreateChatSessionReply) Descriptor() ([]byte, []int) {
	return file_oneRobot_v1_robot_proto_rawDescGZIP(), []int{7}
}

func (x *CreateChatSessionReply) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

//
type ListChatSessionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListChatSessionReq) Reset() {
	*x = ListChatSessionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneRobot_v1_robot_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListChatSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatSessionReq) ProtoMessage() {}

func (x *ListChatSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_oneRobot_v1_robot_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatSessionReq.ProtoReflect.Descriptor instead.
func (*ListChatSessionReq) Descriptor() ([]byte, []int) {
	return file_oneRobot_v1_robot_proto_rawDescGZIP(), []int{8}
}

type ListChatSessionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListChatSessionReply) Reset() {
	*x = ListChatSessionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneRobot_v1_robot_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListChatSessionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatSessionReply) ProtoMessage() {}

func (x *ListChatSessionReply) ProtoReflect() protoreflect.Message {
	mi := &file_oneRobot_v1_robot_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatSessionReply.ProtoReflect.Descriptor instead.
func (*ListChatSessionReply) Descriptor() ([]byte, []int) {
	return file_oneRobot_v1_robot_proto_rawDescGZIP(), []int{9}
}

//
type SendChatSessionMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendChatSessionMsgReq) Reset() {
	*x = SendChatSessionMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneRobot_v1_robot_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendChatSessionMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatSessionMsgReq) ProtoMessage() {}

func (x *SendChatSessionMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_oneRobot_v1_robot_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatSessionMsgReq.ProtoReflect.Descriptor instead.
func (*SendChatSessionMsgReq) Descriptor() ([]byte, []int) {
	return file_oneRobot_v1_robot_proto_rawDescGZIP(), []int{10}
}

type SendChatSessionMsgReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendChatSessionMsgReply) Reset() {
	*x = SendChatSessionMsgReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneRobot_v1_robot_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendChatSessionMsgReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatSessionMsgReply) ProtoMessage() {}

func (x *SendChatSessionMsgReply) ProtoReflect() protoreflect.Message {
	mi := &file_oneRobot_v1_robot_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatSessionMsgReply.ProtoReflect.Descriptor instead.
func (*SendChatSessionMsgReply) Descriptor() ([]byte, []int) {
	return file_oneRobot_v1_robot_proto_rawDescGZIP(), []int{11}
}

// 钉钉交流小助理
type DingTalkBotAssistantReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp                 string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sign                      string `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	MsgId                     string `protobuf:"bytes,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Content                   string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ConversationType          string `protobuf:"bytes,5,opt,name=conversationType,proto3" json:"conversationType,omitempty"`
	ConversationId            string `protobuf:"bytes,6,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	ConversationTitle         string `protobuf:"bytes,7,opt,name=conversationTitle,proto3" json:"conversationTitle,omitempty"`
	SenderCorpId              string `protobuf:"bytes,8,opt,name=senderCorpId,proto3" json:"senderCorpId,omitempty"`
	SenderId                  string `protobuf:"bytes,9,opt,name=senderId,proto3" json:"senderId,omitempty"`
	SenderNick                string `protobuf:"bytes,10,opt,name=senderNick,proto3" json:"senderNick,omitempty"`
	SessionWebhook            string `protobuf:"bytes,11,opt,name=sessionWebhook,proto3" json:"sessionWebhook,omitempty"`
	SessionWebhookExpiredTime int64  `protobuf:"varint,12,opt,name=sessionWebhookExpiredTime,proto3" json:"sessionWebhookExpiredTime,omitempty"`
	IsAdmin                   bool   `protobuf:"varint,13,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	ChatbotCorpId             string `protobuf:"bytes,14,opt,name=chatbotCorpId,proto3" json:"chatbotCorpId,omitempty"`
	IsInAtList                bool   `protobuf:"varint,15,opt,name=isInAtList,proto3" json:"isInAtList,omitempty"`
	SenderStaffId             string `protobuf:"bytes,16,opt,name=senderStaffId,proto3" json:"senderStaffId,omitempty"`
	ChatbotUserId             string `protobuf:"bytes,17,opt,name=chatbotUserId,proto3" json:"chatbotUserId,omitempty"`
	BizSessionId              string `protobuf:"bytes,18,opt,name=bizSessionId,proto3" json:"bizSessionId,omitempty"`
}

func (x *DingTalkBotAssistantReq) Reset() {
	*x = DingTalkBotAssistantReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneRobot_v1_robot_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DingTalkBotAssistantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DingTalkBotAssistantReq) ProtoMessage() {}

func (x *DingTalkBotAssistantReq) ProtoReflect() protoreflect.Message {
	mi := &file_oneRobot_v1_robot_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DingTalkBotAssistantReq.ProtoReflect.Descriptor instead.
func (*DingTalkBotAssistantReq) Descriptor() ([]byte, []int) {
	return file_oneRobot_v1_robot_proto_rawDescGZIP(), []int{12}
}

func (x *DingTalkBotAssistantReq) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *DingTalkBotAssistantReq) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *DingTalkBotAssistantReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *DingTalkBotAssistantReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DingTalkBotAssistantReq) GetConversationType() string {
	if x != nil {
		return x.ConversationType
	}
	return ""
}

func (x *DingTalkBotAssistantReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *DingTalkBotAssistantReq) GetConversationTitle() string {
	if x != nil {
		return x.ConversationTitle
	}
	return ""
}

func (x *DingTalkBotAssistantReq) GetSenderCorpId() string {
	if x != nil {
		return x.SenderCorpId
	}
	return ""
}

func (x *DingTalkBotAssistantReq) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *DingTalkBotAssistantReq) GetSenderNick() string {
	if x != nil {
		return x.SenderNick
	}
	return ""
}

func (x *DingTalkBotAssistantReq) GetSessionWebhook() string {
	if x != nil {
		return x.SessionWebhook
	}
	return ""
}

func (x *DingTalkBotAssistantReq) GetSessionWebhookExpiredTime() int64 {
	if x != nil {
		return x.SessionWebhookExpiredTime
	}
	return 0
}

func (x *DingTalkBotAssistantReq) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *DingTalkBotAssistantReq) GetChatbotCorpId() string {
	if x != nil {
		return x.ChatbotCorpId
	}
	return ""
}

func (x *DingTalkBotAssistantReq) GetIsInAtList() bool {
	if x != nil {
		return x.IsInAtList
	}
	return false
}

func (x *DingTalkBotAssistantReq) GetSenderStaffId() string {
	if x != nil {
		return x.SenderStaffId
	}
	return ""
}

func (x *DingTalkBotAssistantReq) GetChatbotUserId() string {
	if x != nil {
		return x.ChatbotUserId
	}
	return ""
}

func (x *DingTalkBotAssistantReq) GetBizSessionId() string {
	if x != nil {
		return x.BizSessionId
	}
	return ""
}

type DingTalkBotAssistantReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DingTalkBotAssistantReply) Reset() {
	*x = DingTalkBotAssistantReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneRobot_v1_robot_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DingTalkBotAssistantReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DingTalkBotAssistantReply) ProtoMessage() {}

func (x *DingTalkBotAssistantReply) ProtoReflect() protoreflect.Message {
	mi := &file_oneRobot_v1_robot_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DingTalkBotAssistantReply.ProtoReflect.Descriptor instead.
func (*DingTalkBotAssistantReply) Descriptor() ([]byte, []int) {
	return file_oneRobot_v1_robot_proto_rawDescGZIP(), []int{13}
}

func (x *DingTalkBotAssistantReply) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type GetThirdChatWsInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserUuid string `protobuf:"bytes,1,opt,name=userUuid,proto3" json:"userUuid,omitempty"`
}

func (x *GetThirdChatWsInfoReq) Reset() {
	*x = GetThirdChatWsInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneRobot_v1_robot_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetThirdChatWsInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThirdChatWsInfoReq) ProtoMessage() {}

func (x *GetThirdChatWsInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_oneRobot_v1_robot_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThirdChatWsInfoReq.ProtoReflect.Descriptor instead.
func (*GetThirdChatWsInfoReq) Descriptor() ([]byte, []int) {
	return file_oneRobot_v1_robot_proto_rawDescGZIP(), []int{14}
}

func (x *GetThirdChatWsInfoReq) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type GetThirdChatWsInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgUuid   string `protobuf:"bytes,1,opt,name=orgUuid,proto3" json:"orgUuid,omitempty"`
	AppId     string `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	UserUuid  string `protobuf:"bytes,3,opt,name=userUuid,proto3" json:"userUuid,omitempty"`
	Timestamp int64  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Token     string `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetThirdChatWsInfoReply) Reset() {
	*x = GetThirdChatWsInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneRobot_v1_robot_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetThirdChatWsInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThirdChatWsInfoReply) ProtoMessage() {}

func (x *GetThirdChatWsInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_oneRobot_v1_robot_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThirdChatWsInfoReply.ProtoReflect.Descriptor instead.
func (*GetThirdChatWsInfoReply) Descriptor() ([]byte, []int) {
	return file_oneRobot_v1_robot_proto_rawDescGZIP(), []int{15}
}

func (x *GetThirdChatWsInfoReply) GetOrgUuid() string {
	if x != nil {
		return x.OrgUuid
	}
	return ""
}

func (x *GetThirdChatWsInfoReply) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetThirdChatWsInfoReply) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GetThirdChatWsInfoReply) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetThirdChatWsInfoReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetQuestionHisReply_Question struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionUuid string `protobuf:"bytes,1,opt,name=sessionUuid,proto3" json:"sessionUuid,omitempty"`
	Question    string `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Answer      string `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"` // Reply
	Result      int32  `protobuf:"varint,4,opt,name=result,proto3" json:"result,omitempty"`
	Assistant   int32  `protobuf:"varint,5,opt,name=assistant,proto3" json:"assistant,omitempty"`
	CreateTime  int64  `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
}

func (x *GetQuestionHisReply_Question) Reset() {
	*x = GetQuestionHisReply_Question{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneRobot_v1_robot_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuestionHisReply_Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionHisReply_Question) ProtoMessage() {}

func (x *GetQuestionHisReply_Question) ProtoReflect() protoreflect.Message {
	mi := &file_oneRobot_v1_robot_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionHisReply_Question.ProtoReflect.Descriptor instead.
func (*GetQuestionHisReply_Question) Descriptor() ([]byte, []int) {
	return file_oneRobot_v1_robot_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetQuestionHisReply_Question) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

func (x *GetQuestionHisReply_Question) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *GetQuestionHisReply_Question) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *GetQuestionHisReply_Question) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *GetQuestionHisReply_Question) GetAssistant() int32 {
	if x != nil {
		return x.Assistant
	}
	return 0
}

func (x *GetQuestionHisReply_Question) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

var File_oneRobot_v1_robot_proto protoreflect.FileDescriptor

var file_oneRobot_v1_robot_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6f, 0x6e, 0x65, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x6f,
	0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x2e, 0x76, 0x31, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x01, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x12, 0x23, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x07, 0x6f, 0x72, 0x67, 0x55, 0x75,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10,
	0x01, 0x52, 0x07, 0x6f, 0x72, 0x67, 0x55, 0x75, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x08, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x2d, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x5c,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72,
	0x67, 0x55, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x67,
	0x55, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0xbc, 0x01, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x20, 0x0a, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x55, 0x75, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x49, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x6f, 0x72, 0x67, 0x55, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f,
	0x72, 0x67, 0x55, 0x75, 0x69, 0x64, 0x22, 0x94, 0x02, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x44,
	0x0a, 0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x1a, 0xb6, 0x01, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x55, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x55,
	0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x36, 0x0a,
	0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52,
	0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x30, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x68, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x68, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x22, 0x16, 0x0a,
	0x14, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x61,
	0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x22, 0x19,
	0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x93, 0x05, 0x0a, 0x17, 0x44, 0x69,
	0x6e, 0x67, 0x54, 0x61, 0x6c, 0x6b, 0x42, 0x6f, 0x74, 0x41, 0x73, 0x73, 0x69, 0x73, 0x74, 0x61,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x76, 0x65,
	0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x63,
	0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x43, 0x6f, 0x72, 0x70, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x72, 0x70, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x4e, 0x69, 0x63, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x69, 0x63, 0x6b, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f,
	0x6b, 0x12, 0x3c, 0x0a, 0x19, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x57, 0x65, 0x62, 0x68,
	0x6f, 0x6f, 0x6b, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x19, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x57, 0x65, 0x62,
	0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x69, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x69, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x68, 0x61,
	0x74, 0x62, 0x6f, 0x74, 0x43, 0x6f, 0x72, 0x70, 0x49, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x63, 0x68, 0x61, 0x74, 0x62, 0x6f, 0x74, 0x43, 0x6f, 0x72, 0x70, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x49, 0x6e, 0x41, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x49, 0x6e, 0x41, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x24, 0x0a, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x66, 0x66, 0x49, 0x64,
	0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x68, 0x61, 0x74, 0x62, 0x6f, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x68,
	0x61, 0x74, 0x62, 0x6f, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x62,
	0x69, 0x7a, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x12, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x62, 0x69, 0x7a, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22,
	0x33, 0x0a, 0x19, 0x44, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x6c, 0x6b, 0x42, 0x6f, 0x74, 0x41, 0x73,
	0x73, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x33, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x68, 0x69, 0x72, 0x64,
	0x43, 0x68, 0x61, 0x74, 0x57, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x22, 0x99, 0x01, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x54, 0x68, 0x69, 0x72, 0x64, 0x43, 0x68, 0x61, 0x74, 0x57, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x67, 0x55, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x67, 0x55, 0x75, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x9e, 0x05, 0x0a, 0x05, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12,
	0x4c, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1b, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1d,
	0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3d, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x72, 0x6f, 0x62,
	0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x18, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4c, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x12, 0x1b,
	0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x72, 0x6f,
	0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x69, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x55, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1e, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a,
	0x20, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x4f, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x58, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x1f, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x72, 0x6f, 0x62, 0x6f,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5e, 0x0a, 0x14,
	0x44, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x6c, 0x6b, 0x42, 0x6f, 0x74, 0x41, 0x73, 0x73, 0x69, 0x73,
	0x74, 0x61, 0x6e, 0x74, 0x12, 0x21, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x6c, 0x6b, 0x42, 0x6f, 0x74, 0x41, 0x73, 0x73, 0x69, 0x73,
	0x74, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x6c, 0x6b, 0x42, 0x6f, 0x74, 0x41, 0x73,
	0x73, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x58, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x54, 0x68, 0x69, 0x72, 0x64, 0x43, 0x68, 0x61, 0x74, 0x57, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1f, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x68, 0x69, 0x72, 0x64, 0x43, 0x68, 0x61, 0x74, 0x57, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x68, 0x69, 0x72, 0x64, 0x43, 0x68, 0x61, 0x74, 0x57, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x17, 0x5a, 0x15, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_oneRobot_v1_robot_proto_rawDescOnce sync.Once
	file_oneRobot_v1_robot_proto_rawDescData = file_oneRobot_v1_robot_proto_rawDesc
)

func file_oneRobot_v1_robot_proto_rawDescGZIP() []byte {
	file_oneRobot_v1_robot_proto_rawDescOnce.Do(func() {
		file_oneRobot_v1_robot_proto_rawDescData = protoimpl.X.CompressGZIP(file_oneRobot_v1_robot_proto_rawDescData)
	})
	return file_oneRobot_v1_robot_proto_rawDescData
}

var file_oneRobot_v1_robot_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_oneRobot_v1_robot_proto_goTypes = []interface{}{
	(*CreateQuestionReq)(nil),            // 0: robot.v1.CreateQuestionReq
	(*CreateQuestionReply)(nil),          // 1: robot.v1.CreateQuestionReply
	(*GetAnswerReq)(nil),                 // 2: robot.v1.GetAnswerReq
	(*GetAnswerReply)(nil),               // 3: robot.v1.GetAnswerReply
	(*GetQuestionHisReq)(nil),            // 4: robot.v1.GetQuestionHisReq
	(*GetQuestionHisReply)(nil),          // 5: robot.v1.GetQuestionHisReply
	(*CreateChatSessionReq)(nil),         // 6: robot.v1.CreateChatSessionReq
	(*CreateChatSessionReply)(nil),       // 7: robot.v1.CreateChatSessionReply
	(*ListChatSessionReq)(nil),           // 8: robot.v1.ListChatSessionReq
	(*ListChatSessionReply)(nil),         // 9: robot.v1.ListChatSessionReply
	(*SendChatSessionMsgReq)(nil),        // 10: robot.v1.SendChatSessionMsgReq
	(*SendChatSessionMsgReply)(nil),      // 11: robot.v1.SendChatSessionMsgReply
	(*DingTalkBotAssistantReq)(nil),      // 12: robot.v1.DingTalkBotAssistantReq
	(*DingTalkBotAssistantReply)(nil),    // 13: robot.v1.DingTalkBotAssistantReply
	(*GetThirdChatWsInfoReq)(nil),        // 14: robot.v1.GetThirdChatWsInfoReq
	(*GetThirdChatWsInfoReply)(nil),      // 15: robot.v1.GetThirdChatWsInfoReply
	(*GetQuestionHisReply_Question)(nil), // 16: robot.v1.GetQuestionHisReply.Question
}
var file_oneRobot_v1_robot_proto_depIdxs = []int32{
	16, // 0: robot.v1.GetQuestionHisReply.questions:type_name -> robot.v1.GetQuestionHisReply.Question
	0,  // 1: robot.v1.Robot.CreateQuestion:input_type -> robot.v1.CreateQuestionReq
	2,  // 2: robot.v1.Robot.GetAnswer:input_type -> robot.v1.GetAnswerReq
	4,  // 3: robot.v1.Robot.GetQuestionHis:input_type -> robot.v1.GetQuestionHisReq
	6,  // 4: robot.v1.Robot.CreateChatSession:input_type -> robot.v1.CreateChatSessionReq
	8,  // 5: robot.v1.Robot.ListChatSession:input_type -> robot.v1.ListChatSessionReq
	10, // 6: robot.v1.Robot.SendChatSessionMsg:input_type -> robot.v1.SendChatSessionMsgReq
	12, // 7: robot.v1.Robot.DingTalkBotAssistant:input_type -> robot.v1.DingTalkBotAssistantReq
	14, // 8: robot.v1.Robot.GetThirdChatWsInfo:input_type -> robot.v1.GetThirdChatWsInfoReq
	1,  // 9: robot.v1.Robot.CreateQuestion:output_type -> robot.v1.CreateQuestionReply
	3,  // 10: robot.v1.Robot.GetAnswer:output_type -> robot.v1.GetAnswerReply
	5,  // 11: robot.v1.Robot.GetQuestionHis:output_type -> robot.v1.GetQuestionHisReply
	7,  // 12: robot.v1.Robot.CreateChatSession:output_type -> robot.v1.CreateChatSessionReply
	9,  // 13: robot.v1.Robot.ListChatSession:output_type -> robot.v1.ListChatSessionReply
	11, // 14: robot.v1.Robot.SendChatSessionMsg:output_type -> robot.v1.SendChatSessionMsgReply
	13, // 15: robot.v1.Robot.DingTalkBotAssistant:output_type -> robot.v1.DingTalkBotAssistantReply
	15, // 16: robot.v1.Robot.GetThirdChatWsInfo:output_type -> robot.v1.GetThirdChatWsInfoReply
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_oneRobot_v1_robot_proto_init() }
func file_oneRobot_v1_robot_proto_init() {
	if File_oneRobot_v1_robot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_oneRobot_v1_robot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQuestionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneRobot_v1_robot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQuestionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneRobot_v1_robot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnswerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneRobot_v1_robot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnswerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneRobot_v1_robot_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuestionHisReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneRobot_v1_robot_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuestionHisReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneRobot_v1_robot_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatSessionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneRobot_v1_robot_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatSessionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneRobot_v1_robot_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListChatSessionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneRobot_v1_robot_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListChatSessionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneRobot_v1_robot_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendChatSessionMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneRobot_v1_robot_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendChatSessionMsgReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneRobot_v1_robot_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DingTalkBotAssistantReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneRobot_v1_robot_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DingTalkBotAssistantReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneRobot_v1_robot_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetThirdChatWsInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneRobot_v1_robot_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetThirdChatWsInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneRobot_v1_robot_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuestionHisReply_Question); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oneRobot_v1_robot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oneRobot_v1_robot_proto_goTypes,
		DependencyIndexes: file_oneRobot_v1_robot_proto_depIdxs,
		MessageInfos:      file_oneRobot_v1_robot_proto_msgTypes,
	}.Build()
	File_oneRobot_v1_robot_proto = out.File
	file_oneRobot_v1_robot_proto_rawDesc = nil
	file_oneRobot_v1_robot_proto_goTypes = nil
	file_oneRobot_v1_robot_proto_depIdxs = nil
}
