// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.14.0
// source: middleware/v1/middleware.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseIPReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpAddr string `protobuf:"bytes,1,opt,name=ipAddr,proto3" json:"ipAddr,omitempty"`
}

func (x *ParseIPReq) Reset() {
	*x = ParseIPReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_middleware_v1_middleware_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseIPReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseIPReq) ProtoMessage() {}

func (x *ParseIPReq) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_v1_middleware_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseIPReq.ProtoReflect.Descriptor instead.
func (*ParseIPReq) Descriptor() ([]byte, []int) {
	return file_middleware_v1_middleware_proto_rawDescGZIP(), []int{0}
}

func (x *ParseIPReq) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

type ParseIPReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ParseIPReply) Reset() {
	*x = ParseIPReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_middleware_v1_middleware_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseIPReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseIPReply) ProtoMessage() {}

func (x *ParseIPReply) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_v1_middleware_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseIPReply.ProtoReflect.Descriptor instead.
func (*ParseIPReply) Descriptor() ([]byte, []int) {
	return file_middleware_v1_middleware_proto_rawDescGZIP(), []int{1}
}

var File_middleware_v1_middleware_proto protoreflect.FileDescriptor

var file_middleware_v1_middleware_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f,
	0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x6f, 0x6e, 0x65, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2e,
	0x76, 0x31, 0x22, 0x24, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x73, 0x65, 0x49, 0x50, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x61, 0x72, 0x73,
	0x65, 0x49, 0x50, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x58, 0x0a, 0x0d, 0x6f, 0x6e, 0x65, 0x4d,
	0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x12, 0x47, 0x0a, 0x07, 0x50, 0x61, 0x72,
	0x73, 0x65, 0x49, 0x50, 0x12, 0x1c, 0x2e, 0x6f, 0x6e, 0x65, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65,
	0x77, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x49, 0x50, 0x52,
	0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x6f, 0x6e, 0x65, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61,
	0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x49, 0x50, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x6f, 0x70, 0x73, 0x7a, 0x2f, 0x6f, 0x6e, 0x65, 0x4d, 0x69,
	0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x69, 0x64,
	0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_middleware_v1_middleware_proto_rawDescOnce sync.Once
	file_middleware_v1_middleware_proto_rawDescData = file_middleware_v1_middleware_proto_rawDesc
)

func file_middleware_v1_middleware_proto_rawDescGZIP() []byte {
	file_middleware_v1_middleware_proto_rawDescOnce.Do(func() {
		file_middleware_v1_middleware_proto_rawDescData = protoimpl.X.CompressGZIP(file_middleware_v1_middleware_proto_rawDescData)
	})
	return file_middleware_v1_middleware_proto_rawDescData
}

var file_middleware_v1_middleware_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_middleware_v1_middleware_proto_goTypes = []interface{}{
	(*ParseIPReq)(nil),   // 0: oneMiddleware.v1.ParseIPReq
	(*ParseIPReply)(nil), // 1: oneMiddleware.v1.ParseIPReply
}
var file_middleware_v1_middleware_proto_depIdxs = []int32{
	0, // 0: oneMiddleware.v1.oneMiddleware.ParseIP:input_type -> oneMiddleware.v1.ParseIPReq
	1, // 1: oneMiddleware.v1.oneMiddleware.ParseIP:output_type -> oneMiddleware.v1.ParseIPReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_middleware_v1_middleware_proto_init() }
func file_middleware_v1_middleware_proto_init() {
	if File_middleware_v1_middleware_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_middleware_v1_middleware_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseIPReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_middleware_v1_middleware_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseIPReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_middleware_v1_middleware_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_middleware_v1_middleware_proto_goTypes,
		DependencyIndexes: file_middleware_v1_middleware_proto_depIdxs,
		MessageInfos:      file_middleware_v1_middleware_proto_msgTypes,
	}.Build()
	File_middleware_v1_middleware_proto = out.File
	file_middleware_v1_middleware_proto_rawDesc = nil
	file_middleware_v1_middleware_proto_goTypes = nil
	file_middleware_v1_middleware_proto_depIdxs = nil
}
