// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.14.0
// source: jumpServer/v1/jumpServer.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddUserPublicKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserUuid  string `protobuf:"bytes,1,opt,name=userUuid,proto3" json:"userUuid,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PublicKey string `protobuf:"bytes,3,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
}

func (x *AddUserPublicKeyReq) Reset() {
	*x = AddUserPublicKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserPublicKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserPublicKeyReq) ProtoMessage() {}

func (x *AddUserPublicKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserPublicKeyReq.ProtoReflect.Descriptor instead.
func (*AddUserPublicKeyReq) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{0}
}

func (x *AddUserPublicKeyReq) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *AddUserPublicKeyReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddUserPublicKeyReq) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type AddUserPublicKeyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AddUserPublicKeyReply) Reset() {
	*x = AddUserPublicKeyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserPublicKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserPublicKeyReply) ProtoMessage() {}

func (x *AddUserPublicKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserPublicKeyReply.ProtoReflect.Descriptor instead.
func (*AddUserPublicKeyReply) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{1}
}

func (x *AddUserPublicKeyReply) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type UpdateUserPublicKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserUuid  string `protobuf:"bytes,1,opt,name=userUuid,proto3" json:"userUuid,omitempty"`
	PublicKey string `protobuf:"bytes,3,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
}

func (x *UpdateUserPublicKeyReq) Reset() {
	*x = UpdateUserPublicKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserPublicKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPublicKeyReq) ProtoMessage() {}

func (x *UpdateUserPublicKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPublicKeyReq.ProtoReflect.Descriptor instead.
func (*UpdateUserPublicKeyReq) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserPublicKeyReq) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UpdateUserPublicKeyReq) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type UpdateUserPublicKeyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *UpdateUserPublicKeyReply) Reset() {
	*x = UpdateUserPublicKeyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserPublicKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPublicKeyReply) ProtoMessage() {}

func (x *UpdateUserPublicKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPublicKeyReply.ProtoReflect.Descriptor instead.
func (*UpdateUserPublicKeyReply) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserPublicKeyReply) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type GetUserPublicKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserUuid string `protobuf:"bytes,1,opt,name=userUuid,proto3" json:"userUuid,omitempty"`
}

func (x *GetUserPublicKeyReq) Reset() {
	*x = GetUserPublicKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPublicKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPublicKeyReq) ProtoMessage() {}

func (x *GetUserPublicKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPublicKeyReq.ProtoReflect.Descriptor instead.
func (*GetUserPublicKeyReq) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserPublicKeyReq) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type GetUserPublicKeyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey  string `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	CreateTime int64  `protobuf:"varint,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
}

func (x *GetUserPublicKeyReply) Reset() {
	*x = GetUserPublicKeyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPublicKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPublicKeyReply) ProtoMessage() {}

func (x *GetUserPublicKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPublicKeyReply.ProtoReflect.Descriptor instead.
func (*GetUserPublicKeyReply) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserPublicKeyReply) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *GetUserPublicKeyReply) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type DelUserPublicKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserUuid string `protobuf:"bytes,1,opt,name=userUuid,proto3" json:"userUuid,omitempty"`
}

func (x *DelUserPublicKeyReq) Reset() {
	*x = DelUserPublicKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelUserPublicKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserPublicKeyReq) ProtoMessage() {}

func (x *DelUserPublicKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserPublicKeyReq.ProtoReflect.Descriptor instead.
func (*DelUserPublicKeyReq) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{6}
}

func (x *DelUserPublicKeyReq) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type DelUserPublicKeyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DelUserPublicKeyReply) Reset() {
	*x = DelUserPublicKeyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelUserPublicKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserPublicKeyReply) ProtoMessage() {}

func (x *DelUserPublicKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserPublicKeyReply.ProtoReflect.Descriptor instead.
func (*DelUserPublicKeyReply) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{7}
}

func (x *DelUserPublicKeyReply) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type GeneratePrivateKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passphrase string `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
}

func (x *GeneratePrivateKeyReq) Reset() {
	*x = GeneratePrivateKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratePrivateKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePrivateKeyReq) ProtoMessage() {}

func (x *GeneratePrivateKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePrivateKeyReq.ProtoReflect.Descriptor instead.
func (*GeneratePrivateKeyReq) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{8}
}

func (x *GeneratePrivateKeyReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GeneratePrivateKeyReq) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

type GeneratePrivateKeyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GeneratePrivateKeyReply) Reset() {
	*x = GeneratePrivateKeyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratePrivateKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePrivateKeyReply) ProtoMessage() {}

func (x *GeneratePrivateKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePrivateKeyReply.ProtoReflect.Descriptor instead.
func (*GeneratePrivateKeyReply) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{9}
}

func (x *GeneratePrivateKeyReply) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type ListPrivateKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPrivateKeyReq) Reset() {
	*x = ListPrivateKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPrivateKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrivateKeyReq) ProtoMessage() {}

func (x *ListPrivateKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrivateKeyReq.ProtoReflect.Descriptor instead.
func (*ListPrivateKeyReq) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{10}
}

type ListPrivateKeyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey []*ListPrivateKeyReply_PrivateKey `protobuf:"bytes,1,rep,name=privateKey,proto3" json:"privateKey,omitempty"`
}

func (x *ListPrivateKeyReply) Reset() {
	*x = ListPrivateKeyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPrivateKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrivateKeyReply) ProtoMessage() {}

func (x *ListPrivateKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrivateKeyReply.ProtoReflect.Descriptor instead.
func (*ListPrivateKeyReply) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{11}
}

func (x *ListPrivateKeyReply) GetPrivateKey() []*ListPrivateKeyReply_PrivateKey {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

type GetPrivateKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *GetPrivateKeyReq) Reset() {
	*x = GetPrivateKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPrivateKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateKeyReq) ProtoMessage() {}

func (x *GetPrivateKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateKeyReq.ProtoReflect.Descriptor instead.
func (*GetPrivateKeyReq) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{12}
}

func (x *GetPrivateKeyReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetPrivateKeyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PrivateKey    string `protobuf:"bytes,3,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	PublicKey     string `protobuf:"bytes,4,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	HasPassphrase bool   `protobuf:"varint,5,opt,name=hasPassphrase,proto3" json:"hasPassphrase,omitempty"`
	CreateTime    int64  `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
}

func (x *GetPrivateKeyReply) Reset() {
	*x = GetPrivateKeyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPrivateKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateKeyReply) ProtoMessage() {}

func (x *GetPrivateKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateKeyReply.ProtoReflect.Descriptor instead.
func (*GetPrivateKeyReply) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{13}
}

func (x *GetPrivateKeyReply) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetPrivateKeyReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPrivateKeyReply) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *GetPrivateKeyReply) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *GetPrivateKeyReply) GetHasPassphrase() bool {
	if x != nil {
		return x.HasPassphrase
	}
	return false
}

func (x *GetPrivateKeyReply) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type DelPrivateKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *DelPrivateKeyReq) Reset() {
	*x = DelPrivateKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelPrivateKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelPrivateKeyReq) ProtoMessage() {}

func (x *DelPrivateKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelPrivateKeyReq.ProtoReflect.Descriptor instead.
func (*DelPrivateKeyReq) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{14}
}

func (x *DelPrivateKeyReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DelPrivateKeyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DelPrivateKeyReply) Reset() {
	*x = DelPrivateKeyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelPrivateKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelPrivateKeyReply) ProtoMessage() {}

func (x *DelPrivateKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelPrivateKeyReply.ProtoReflect.Descriptor instead.
func (*DelPrivateKeyReply) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{15}
}

func (x *DelPrivateKeyReply) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type AddDomainReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PrivateKeyUuid string `protobuf:"bytes,2,opt,name=privateKeyUuid,proto3" json:"privateKeyUuid,omitempty"`
}

func (x *AddDomainReq) Reset() {
	*x = AddDomainReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDomainReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDomainReq) ProtoMessage() {}

func (x *AddDomainReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDomainReq.ProtoReflect.Descriptor instead.
func (*AddDomainReq) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{16}
}

func (x *AddDomainReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddDomainReq) GetPrivateKeyUuid() string {
	if x != nil {
		return x.PrivateKeyUuid
	}
	return ""
}

type AddDomainReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AddDomainReply) Reset() {
	*x = AddDomainReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDomainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDomainReply) ProtoMessage() {}

func (x *AddDomainReply) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDomainReply.ProtoReflect.Descriptor instead.
func (*AddDomainReply) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{17}
}

func (x *AddDomainReply) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type ListDomainReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListDomainReq) Reset() {
	*x = ListDomainReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDomainReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainReq) ProtoMessage() {}

func (x *ListDomainReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainReq.ProtoReflect.Descriptor instead.
func (*ListDomainReq) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{18}
}

type ListDomainReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domains []*ListDomainReply_Domain `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
}

func (x *ListDomainReply) Reset() {
	*x = ListDomainReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDomainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainReply) ProtoMessage() {}

func (x *ListDomainReply) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainReply.ProtoReflect.Descriptor instead.
func (*ListDomainReply) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{19}
}

func (x *ListDomainReply) GetDomains() []*ListDomainReply_Domain {
	if x != nil {
		return x.Domains
	}
	return nil
}

type AddHostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IpAddr     string `protobuf:"bytes,3,opt,name=ipAddr,proto3" json:"ipAddr,omitempty"`
	Port       int32  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	DomainUuid string `protobuf:"bytes,2,opt,name=domainUuid,proto3" json:"domainUuid,omitempty"`
}

func (x *AddHostReq) Reset() {
	*x = AddHostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddHostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHostReq) ProtoMessage() {}

func (x *AddHostReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHostReq.ProtoReflect.Descriptor instead.
func (*AddHostReq) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{20}
}

func (x *AddHostReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddHostReq) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

func (x *AddHostReq) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AddHostReq) GetDomainUuid() string {
	if x != nil {
		return x.DomainUuid
	}
	return ""
}

type AddHostReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AddHostReply) Reset() {
	*x = AddHostReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddHostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHostReply) ProtoMessage() {}

func (x *AddHostReply) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHostReply.ProtoReflect.Descriptor instead.
func (*AddHostReply) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{21}
}

func (x *AddHostReply) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type ListHostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DomainUuid string `protobuf:"bytes,1,opt,name=domainUuid,proto3" json:"domainUuid,omitempty"`
}

func (x *ListHostReq) Reset() {
	*x = ListHostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostReq) ProtoMessage() {}

func (x *ListHostReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostReq.ProtoReflect.Descriptor instead.
func (*ListHostReq) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{22}
}

func (x *ListHostReq) GetDomainUuid() string {
	if x != nil {
		return x.DomainUuid
	}
	return ""
}

type ListHostReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hosts []*ListHostReply_Host `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
}

func (x *ListHostReply) Reset() {
	*x = ListHostReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostReply) ProtoMessage() {}

func (x *ListHostReply) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostReply.ProtoReflect.Descriptor instead.
func (*ListHostReply) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{23}
}

func (x *ListHostReply) GetHosts() []*ListHostReply_Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type DelHostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *DelHostReq) Reset() {
	*x = DelHostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelHostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelHostReq) ProtoMessage() {}

func (x *DelHostReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelHostReq.ProtoReflect.Descriptor instead.
func (*DelHostReq) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{24}
}

func (x *DelHostReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DelHostReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DelHostReply) Reset() {
	*x = DelHostReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelHostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelHostReply) ProtoMessage() {}

func (x *DelHostReply) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelHostReply.ProtoReflect.Descriptor instead.
func (*DelHostReply) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{25}
}

func (x *DelHostReply) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type ListPrivateKeyReply_PrivateKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PrivateKey    string `protobuf:"bytes,3,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	PublicKey     string `protobuf:"bytes,4,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	HasPassphrase bool   `protobuf:"varint,5,opt,name=hasPassphrase,proto3" json:"hasPassphrase,omitempty"`
	CreateTime    int64  `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
}

func (x *ListPrivateKeyReply_PrivateKey) Reset() {
	*x = ListPrivateKeyReply_PrivateKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPrivateKeyReply_PrivateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrivateKeyReply_PrivateKey) ProtoMessage() {}

func (x *ListPrivateKeyReply_PrivateKey) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrivateKeyReply_PrivateKey.ProtoReflect.Descriptor instead.
func (*ListPrivateKeyReply_PrivateKey) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{11, 0}
}

func (x *ListPrivateKeyReply_PrivateKey) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ListPrivateKeyReply_PrivateKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListPrivateKeyReply_PrivateKey) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *ListPrivateKeyReply_PrivateKey) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ListPrivateKeyReply_PrivateKey) GetHasPassphrase() bool {
	if x != nil {
		return x.HasPassphrase
	}
	return false
}

func (x *ListPrivateKeyReply_PrivateKey) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type ListDomainReply_Domain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid           string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PrivateKeyUuid string `protobuf:"bytes,3,opt,name=privateKeyUuid,proto3" json:"privateKeyUuid,omitempty"`
}

func (x *ListDomainReply_Domain) Reset() {
	*x = ListDomainReply_Domain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDomainReply_Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainReply_Domain) ProtoMessage() {}

func (x *ListDomainReply_Domain) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainReply_Domain.ProtoReflect.Descriptor instead.
func (*ListDomainReply_Domain) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{19, 0}
}

func (x *ListDomainReply_Domain) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ListDomainReply_Domain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListDomainReply_Domain) GetPrivateKeyUuid() string {
	if x != nil {
		return x.PrivateKeyUuid
	}
	return ""
}

type ListHostReply_Host struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid       string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	DomainUuid string `protobuf:"bytes,2,opt,name=domainUuid,proto3" json:"domainUuid,omitempty"`
	Hostname   string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddr     string `protobuf:"bytes,4,opt,name=ipAddr,proto3" json:"ipAddr,omitempty"`
	SshPort    int32  `protobuf:"varint,5,opt,name=sshPort,proto3" json:"sshPort,omitempty"`
	CreateTime int64  `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
}

func (x *ListHostReply_Host) Reset() {
	*x = ListHostReply_Host{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHostReply_Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostReply_Host) ProtoMessage() {}

func (x *ListHostReply_Host) ProtoReflect() protoreflect.Message {
	mi := &file_jumpServer_v1_jumpServer_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostReply_Host.ProtoReflect.Descriptor instead.
func (*ListHostReply_Host) Descriptor() ([]byte, []int) {
	return file_jumpServer_v1_jumpServer_proto_rawDescGZIP(), []int{23, 0}
}

func (x *ListHostReply_Host) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ListHostReply_Host) GetDomainUuid() string {
	if x != nil {
		return x.DomainUuid
	}
	return ""
}

func (x *ListHostReply_Host) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ListHostReply_Host) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

func (x *ListHostReply_Host) GetSshPort() int32 {
	if x != nil {
		return x.SshPort
	}
	return 0
}

func (x *ListHostReply_Host) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

var File_jumpServer_v1_jumpServer_proto protoreflect.FileDescriptor

var file_jumpServer_v1_jumpServer_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f,
	0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a,
	0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x01, 0x0a, 0x13, 0x41, 0x64, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71,
	0x12, 0x23, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x22, 0x2f, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x64, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69,
	0x64, 0x12, 0x25, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x32, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x31, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x22,
	0x55, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75,
	0x69, 0x64, 0x22, 0x2f, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x54, 0x0a, 0x15, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72,
	0x02, 0x10, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x73,
	0x73, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70,
	0x61, 0x73, 0x73, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x22, 0x31, 0x0a, 0x17, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x13, 0x0a, 0x11,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x71, 0x22, 0x9f, 0x02, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4d, 0x0a, 0x0a, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e,
	0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x0a, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x1a, 0xb8, 0x01, 0x0a, 0x0a, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a,
	0x0d, 0x68, 0x61, 0x73, 0x50, 0x61, 0x73, 0x73, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x68, 0x61, 0x73, 0x50, 0x61, 0x73, 0x73, 0x70, 0x68, 0x72,
	0x61, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x22, 0xc0, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x12, 0x24, 0x0a, 0x0d, 0x68, 0x61, 0x73, 0x50, 0x61, 0x73, 0x73, 0x70, 0x68, 0x72, 0x61,
	0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x68, 0x61, 0x73, 0x50, 0x61, 0x73,
	0x73, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02,
	0x10, 0x01, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x5c, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x44, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x0e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x55, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x72, 0x02, 0x10, 0x01, 0x52, 0x0e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79,
	0x55, 0x75, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x0f,
	0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x22,
	0xac, 0x01, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x3f, 0x0a, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x07, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x73, 0x1a, 0x58, 0x0a, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x55, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x55, 0x75, 0x69, 0x64, 0x22, 0x87,
	0x01, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x72, 0x02, 0x10, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x69, 0x70,
	0x41, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72,
	0x02, 0x10, 0x01, 0x52, 0x06, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x27, 0x0a, 0x0a, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x0a, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x48,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x2d, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x22,
	0xf3, 0x01, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x37, 0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x48,
	0x6f, 0x73, 0x74, 0x52, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x1a, 0xa8, 0x01, 0x0a, 0x04, 0x48,
	0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x55, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x73, 0x68, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x73,
	0x68, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x20, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x48, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x48, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32,
	0xee, 0x08, 0x0a, 0x0a, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x5e,
	0x0a, 0x10, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x12, 0x22, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x67,
	0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x25, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x6a,
	0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x22, 0x2e, 0x6a, 0x75,
	0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x1a,
	0x24, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x22, 0x2e, 0x6a, 0x75,
	0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x1a,
	0x24, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x2e,
	0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x71, 0x1a, 0x26, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x58, 0x0a,
	0x0e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12,
	0x20, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x71, 0x1a, 0x22, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x6a, 0x75, 0x6d, 0x70,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x55,
	0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12,
	0x1f, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x6c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71,
	0x1a, 0x21, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x44, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x12, 0x1b, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a,
	0x1d, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x64, 0x64, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x4c, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1c,
	0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x6a,
	0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x43,
	0x0a, 0x07, 0x41, 0x64, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x6a, 0x75, 0x6d, 0x70,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x12,
	0x1a, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x6a, 0x75,
	0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x07, 0x44,
	0x65, 0x6c, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x1b, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x65, 0x6c, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x4f, 0x70, 0x73, 0x7a, 0x2f, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jumpServer_v1_jumpServer_proto_rawDescOnce sync.Once
	file_jumpServer_v1_jumpServer_proto_rawDescData = file_jumpServer_v1_jumpServer_proto_rawDesc
)

func file_jumpServer_v1_jumpServer_proto_rawDescGZIP() []byte {
	file_jumpServer_v1_jumpServer_proto_rawDescOnce.Do(func() {
		file_jumpServer_v1_jumpServer_proto_rawDescData = protoimpl.X.CompressGZIP(file_jumpServer_v1_jumpServer_proto_rawDescData)
	})
	return file_jumpServer_v1_jumpServer_proto_rawDescData
}

var file_jumpServer_v1_jumpServer_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_jumpServer_v1_jumpServer_proto_goTypes = []interface{}{
	(*AddUserPublicKeyReq)(nil),            // 0: jumpServer.v1.AddUserPublicKeyReq
	(*AddUserPublicKeyReply)(nil),          // 1: jumpServer.v1.AddUserPublicKeyReply
	(*UpdateUserPublicKeyReq)(nil),         // 2: jumpServer.v1.UpdateUserPublicKeyReq
	(*UpdateUserPublicKeyReply)(nil),       // 3: jumpServer.v1.UpdateUserPublicKeyReply
	(*GetUserPublicKeyReq)(nil),            // 4: jumpServer.v1.GetUserPublicKeyReq
	(*GetUserPublicKeyReply)(nil),          // 5: jumpServer.v1.GetUserPublicKeyReply
	(*DelUserPublicKeyReq)(nil),            // 6: jumpServer.v1.DelUserPublicKeyReq
	(*DelUserPublicKeyReply)(nil),          // 7: jumpServer.v1.DelUserPublicKeyReply
	(*GeneratePrivateKeyReq)(nil),          // 8: jumpServer.v1.GeneratePrivateKeyReq
	(*GeneratePrivateKeyReply)(nil),        // 9: jumpServer.v1.GeneratePrivateKeyReply
	(*ListPrivateKeyReq)(nil),              // 10: jumpServer.v1.ListPrivateKeyReq
	(*ListPrivateKeyReply)(nil),            // 11: jumpServer.v1.ListPrivateKeyReply
	(*GetPrivateKeyReq)(nil),               // 12: jumpServer.v1.GetPrivateKeyReq
	(*GetPrivateKeyReply)(nil),             // 13: jumpServer.v1.GetPrivateKeyReply
	(*DelPrivateKeyReq)(nil),               // 14: jumpServer.v1.DelPrivateKeyReq
	(*DelPrivateKeyReply)(nil),             // 15: jumpServer.v1.DelPrivateKeyReply
	(*AddDomainReq)(nil),                   // 16: jumpServer.v1.AddDomainReq
	(*AddDomainReply)(nil),                 // 17: jumpServer.v1.AddDomainReply
	(*ListDomainReq)(nil),                  // 18: jumpServer.v1.ListDomainReq
	(*ListDomainReply)(nil),                // 19: jumpServer.v1.ListDomainReply
	(*AddHostReq)(nil),                     // 20: jumpServer.v1.AddHostReq
	(*AddHostReply)(nil),                   // 21: jumpServer.v1.AddHostReply
	(*ListHostReq)(nil),                    // 22: jumpServer.v1.ListHostReq
	(*ListHostReply)(nil),                  // 23: jumpServer.v1.ListHostReply
	(*DelHostReq)(nil),                     // 24: jumpServer.v1.DelHostReq
	(*DelHostReply)(nil),                   // 25: jumpServer.v1.DelHostReply
	(*ListPrivateKeyReply_PrivateKey)(nil), // 26: jumpServer.v1.ListPrivateKeyReply.PrivateKey
	(*ListDomainReply_Domain)(nil),         // 27: jumpServer.v1.ListDomainReply.Domain
	(*ListHostReply_Host)(nil),             // 28: jumpServer.v1.ListHostReply.Host
}
var file_jumpServer_v1_jumpServer_proto_depIdxs = []int32{
	26, // 0: jumpServer.v1.ListPrivateKeyReply.privateKey:type_name -> jumpServer.v1.ListPrivateKeyReply.PrivateKey
	27, // 1: jumpServer.v1.ListDomainReply.domains:type_name -> jumpServer.v1.ListDomainReply.Domain
	28, // 2: jumpServer.v1.ListHostReply.hosts:type_name -> jumpServer.v1.ListHostReply.Host
	0,  // 3: jumpServer.v1.jumpServer.AddUserPublicKey:input_type -> jumpServer.v1.AddUserPublicKeyReq
	2,  // 4: jumpServer.v1.jumpServer.UpdateUserPublicKey:input_type -> jumpServer.v1.UpdateUserPublicKeyReq
	4,  // 5: jumpServer.v1.jumpServer.GetUserPublicKey:input_type -> jumpServer.v1.GetUserPublicKeyReq
	6,  // 6: jumpServer.v1.jumpServer.DelUserPublicKey:input_type -> jumpServer.v1.DelUserPublicKeyReq
	8,  // 7: jumpServer.v1.jumpServer.GeneratePrivateKey:input_type -> jumpServer.v1.GeneratePrivateKeyReq
	10, // 8: jumpServer.v1.jumpServer.ListPrivateKey:input_type -> jumpServer.v1.ListPrivateKeyReq
	12, // 9: jumpServer.v1.jumpServer.GetPrivateKey:input_type -> jumpServer.v1.GetPrivateKeyReq
	14, // 10: jumpServer.v1.jumpServer.DelPrivateKey:input_type -> jumpServer.v1.DelPrivateKeyReq
	16, // 11: jumpServer.v1.jumpServer.AddDomain:input_type -> jumpServer.v1.AddDomainReq
	18, // 12: jumpServer.v1.jumpServer.ListDomain:input_type -> jumpServer.v1.ListDomainReq
	20, // 13: jumpServer.v1.jumpServer.AddHost:input_type -> jumpServer.v1.AddHostReq
	22, // 14: jumpServer.v1.jumpServer.ListHost:input_type -> jumpServer.v1.ListHostReq
	24, // 15: jumpServer.v1.jumpServer.DelHost:input_type -> jumpServer.v1.DelHostReq
	1,  // 16: jumpServer.v1.jumpServer.AddUserPublicKey:output_type -> jumpServer.v1.AddUserPublicKeyReply
	3,  // 17: jumpServer.v1.jumpServer.UpdateUserPublicKey:output_type -> jumpServer.v1.UpdateUserPublicKeyReply
	5,  // 18: jumpServer.v1.jumpServer.GetUserPublicKey:output_type -> jumpServer.v1.GetUserPublicKeyReply
	7,  // 19: jumpServer.v1.jumpServer.DelUserPublicKey:output_type -> jumpServer.v1.DelUserPublicKeyReply
	9,  // 20: jumpServer.v1.jumpServer.GeneratePrivateKey:output_type -> jumpServer.v1.GeneratePrivateKeyReply
	11, // 21: jumpServer.v1.jumpServer.ListPrivateKey:output_type -> jumpServer.v1.ListPrivateKeyReply
	13, // 22: jumpServer.v1.jumpServer.GetPrivateKey:output_type -> jumpServer.v1.GetPrivateKeyReply
	15, // 23: jumpServer.v1.jumpServer.DelPrivateKey:output_type -> jumpServer.v1.DelPrivateKeyReply
	17, // 24: jumpServer.v1.jumpServer.AddDomain:output_type -> jumpServer.v1.AddDomainReply
	19, // 25: jumpServer.v1.jumpServer.ListDomain:output_type -> jumpServer.v1.ListDomainReply
	21, // 26: jumpServer.v1.jumpServer.AddHost:output_type -> jumpServer.v1.AddHostReply
	23, // 27: jumpServer.v1.jumpServer.ListHost:output_type -> jumpServer.v1.ListHostReply
	25, // 28: jumpServer.v1.jumpServer.DelHost:output_type -> jumpServer.v1.DelHostReply
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_jumpServer_v1_jumpServer_proto_init() }
func file_jumpServer_v1_jumpServer_proto_init() {
	if File_jumpServer_v1_jumpServer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jumpServer_v1_jumpServer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUserPublicKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUserPublicKeyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserPublicKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserPublicKeyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPublicKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPublicKeyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelUserPublicKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelUserPublicKeyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneratePrivateKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneratePrivateKeyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPrivateKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPrivateKeyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPrivateKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPrivateKeyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelPrivateKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelPrivateKeyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDomainReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDomainReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDomainReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDomainReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddHostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddHostReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHostReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelHostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelHostReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPrivateKeyReply_PrivateKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDomainReply_Domain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumpServer_v1_jumpServer_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHostReply_Host); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jumpServer_v1_jumpServer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jumpServer_v1_jumpServer_proto_goTypes,
		DependencyIndexes: file_jumpServer_v1_jumpServer_proto_depIdxs,
		MessageInfos:      file_jumpServer_v1_jumpServer_proto_msgTypes,
	}.Build()
	File_jumpServer_v1_jumpServer_proto = out.File
	file_jumpServer_v1_jumpServer_proto_rawDesc = nil
	file_jumpServer_v1_jumpServer_proto_goTypes = nil
	file_jumpServer_v1_jumpServer_proto_depIdxs = nil
}
